'use client';

import { useEffect, useMemo, useState } from 'react';

const questions = [
  {q:'Una persona importante lleva horas sin contestarte. ¿Qué piensas primero?',a:['Estará ocupada','Me pregunto si habrá pasado algo','Repaso nuestra última conversación','Me molesta, aunque intento ignorarlo','Apenas le doy importancia'],tags:[['seguridad'],['empatia','sensibilidad'],['analisis','sensibilidad'],['intensidad'],['autonomia']]},
  {q:'Cuando alguien empieza a gustarte, normalmente...',a:['Tomo la iniciativa','Observo primero','Coqueteo para tantear','Intento disimularlo','Depende muchísimo de la persona'],tags:[['iniciativa'],['analisis'],['humor','iniciativa'],['prudencia'],['adaptacion']]},
  {q:'¿Qué valoras más en una relación?',a:['Constancia','Sinceridad','Libertad','Afecto','Intensidad'],tags:[['constancia'],['sinceridad'],['autonomia'],['afecto'],['intensidad']]},
  {q:'Una discusión importante aparece. Tú...',a:['Quiero resolverla cuanto antes','Necesito tiempo para pensar','Pregunto hasta entender qué ocurre','Intento rebajarla con humor','Me cierro si me siento atacado/a'],tags:[['resolucion'],['prudencia'],['analisis'],['humor'],['sensibilidad']]},
  {q:'¿Qué te cuesta más perdonar?',a:['Una mentira','La indiferencia','Una infidelidad','Una humillación','Que desaparezcan sin explicar nada'],tags:[['sinceridad'],['afecto'],['exclusividad'],['orgullo'],['sensibilidad']]},
  {q:'¿Cuánto pesa la atracción física para ti?',a:['Muy poco','Algo, pero manda la conexión','Importa bastante','Es esencial al principio','Depende totalmente de la persona'],tags:[['conexion'],['conexion'],['atraccion'],['atraccion'],['adaptacion']]},
  {q:'Cuando hay química con alguien...',a:['Voy despacio','Dejo que fluya','Suelo tomar iniciativa','Espero señales claras','Me pongo bastante nervioso/a'],tags:[['prudencia'],['espontaneidad'],['iniciativa'],['reciprocidad'],['sensibilidad']]},
  {q:'¿Qué necesitas para abrirte de verdad?',a:['Tiempo','Confianza','Sentirme escuchado/a','Reciprocidad','Que la otra persona se abra primero'],tags:[['prudencia'],['confianza'],['conexion'],['reciprocidad'],['reciprocidad']]},
  {q:'Si notas un cambio de tono en alguien importante...',a:['Pregunto directamente','Espero a ver qué ocurre','Le doy muchas vueltas','Asumo que tendrá un mal día','Me distancio también'],tags:[['iniciativa'],['prudencia'],['analisis'],['seguridad'],['orgullo']]},
  {q:'Tu relación ideal deja espacio para...',a:['Muchísima independencia','Rutinas compartidas','Hablar todos los días','Improvisar y sorprendernos','Una mezcla de todo'],tags:[['autonomia'],['constancia'],['afecto'],['espontaneidad'],['adaptacion']]},
  {q:'¿Cómo te llevas con la incertidumbre?',a:['Muy bien','Bastante bien','Depende','Me cuesta','La odio'],tags:[['seguridad'],['autonomia'],['adaptacion'],['analisis'],['analisis','sensibilidad']]},
  {q:'Si alguien te atrae pero no sabes si es recíproco...',a:['Se lo digo','Lanzo indirectas','Espero señales','Intento olvidarlo','Sigo conociéndolo sin decidir nada'],tags:[['iniciativa'],['humor'],['reciprocidad'],['autonomia'],['curiosidad']]},
  {q:'Llegas a una fiesta donde apenas conoces a nadie. ¿Qué haces?',a:['Empiezo a hablar con cualquiera','Busco a una persona y tiro desde ahí','Observo antes de moverme','Me quedo cerca de quien conozco','Probablemente me iría pronto'],tags:[['sociabilidad','iniciativa'],['sociabilidad'],['observacion','prudencia'],['timidez'],['timidez','autonomia']]},
  {q:'Alguien hace una broma sobre ti delante de otros...',a:['Me río y sigo','Le devuelvo otra broma','Me molesta pero no lo digo','Le digo que no me ha gustado','Depende de quién sea'],tags:[['seguridad'],['humor','seguridad'],['sensibilidad'],['limites','iniciativa'],['adaptacion']]},
  {q:'Cuando tomas una decisión importante...',a:['Me guío por intuición','Hago una lista mental de pros y contras','Pido opinión a personas cercanas','Le doy vueltas hasta estar seguro/a','Decido rápido y corrijo después'],tags:[['intuicion'],['analisis'],['reciprocidad'],['analisis','perfeccionismo'],['impulsividad','adaptacion']]},
  {q:'Si una persona te cuenta un secreto delicado...',a:['No sale de mí','Intento ayudar aunque no me lo pida','Pregunto para entender mejor','Me preocupa cargar con ello','Depende de lo que sea'],tags:[['lealtad'],['empatia'],['curiosidad','empatia'],['sensibilidad'],['prudencia']]},
  {q:'¿Cómo reaccionas cuando te hacen un cumplido?',a:['Lo agradezco sin problema','Me da vergüenza','Hago una broma','Dudo si lo dicen en serio','Me encanta que me lo digan'],tags:[['seguridad'],['timidez'],['humor'],['inseguridad'],['validacion']]},
  {q:'Una persona que te importa cancela un plan a última hora...',a:['No pasa nada','Pregunto si está bien','Me decepciona bastante','Me enfado si no hay buena razón','Empiezo a preguntarme si evita verme'],tags:[['autonomia'],['empatia'],['sensibilidad'],['orgullo','limites'],['analisis','inseguridad']]},
  {q:'¿Qué describe mejor tu forma de mostrar cariño?',a:['Decir lo que siento','Pasar tiempo juntos','Hacer cosas por la otra persona','Contacto físico','Recordar detalles pequeños'],tags:[['expresividad'],['afecto'],['cuidado'],['contacto'],['observacion','cuidado']]},
  {q:'Cuando estás enfadado/a...',a:['Lo digo enseguida','Necesito aislarme un rato','Intento hablar con calma','Puedo decir cosas impulsivas','Finjo que estoy bien'],tags:[['expresividad'],['autonomia','prudencia'],['regulacion','resolucion'],['impulsividad','intensidad'],['ocultacion']]},
  {q:'¿Qué ocurre cuando alguien piensa muy distinto a ti?',a:['Me encanta debatir','Intento entender de dónde viene','Evito discutir','Defiendo mi postura con fuerza','Depende del tema'],tags:[['curiosidad','iniciativa'],['empatia','curiosidad'],['prudencia'],['intensidad','orgullo'],['adaptacion']]},
  {q:'Si recibes un mensaje muy cariñoso inesperado...',a:['Respondo igual de cariñoso/a','Me hace ilusión pero me corto','Bromeo para quitarle intensidad','Analizo qué significa','Me incomoda si aún no hay confianza'],tags:[['afecto','expresividad'],['timidez','afecto'],['humor'],['analisis'],['limites','prudencia']]},
  {q:'En un grupo de amigos sueles ser...',a:['Quien propone planes','Quien escucha','Quien hace reír','Quien observa todo','Cambio mucho según el grupo'],tags:[['iniciativa','sociabilidad'],['empatia'],['humor','sociabilidad'],['observacion'],['adaptacion']]},
  {q:'Cuando algo te sale mal después de esforzarte...',a:['Vuelvo a intentarlo','Necesito descansar y regreso','Me frustro bastante','Analizo qué falló','Pierdo interés rápido'],tags:[['constancia'],['regulacion'],['intensidad'],['analisis'],['novedad']]},
  {q:'¿Cómo llevas que tu pareja tenga una vida social muy independiente?',a:['Perfectamente','Bien si hay confianza','A veces me genera dudas','Necesito bastante comunicación','Me costaría mucho'],tags:[['autonomia','confianza'],['confianza'],['inseguridad'],['reciprocidad','afecto'],['exclusividad','sensibilidad']]},
  {q:'Descubres que estabas equivocado/a en una discusión...',a:['Lo admito sin problema','Me cuesta, pero lo admito','Intento explicarme antes de admitirlo','Me da mucha vergüenza','A veces sigo defendiendo mi postura'],tags:[['humildad'],['humildad','orgullo'],['orgullo','analisis'],['sensibilidad'],['orgullo']]},
  {q:'Cuando conoces a alguien que te parece muy atractivo/a...',a:['Me acerco si tengo ocasión','Me pongo algo nervioso/a','Observo pero no hago nada','Su físico no cambia mucho mi comportamiento','Intento llamar su atención'],tags:[['iniciativa','atraccion'],['timidez','atraccion'],['observacion','atraccion'],['conexion'],['validacion','iniciativa']]},
  {q:'¿Qué importancia tiene para ti sentirte elegido/a por alguien?',a:['Muy poca','Algo','Bastante','Mucha','Es una necesidad emocional fuerte'],tags:[['autonomia'],['seguridad'],['reciprocidad'],['validacion','afecto'],['validacion','sensibilidad']]},
  {q:'Si sospechas que alguien te oculta algo...',a:['Pregunto directamente','Busco señales antes de preguntar','Espero a que me lo cuente','Me cuesta actuar con normalidad','Intento no pensar en ello'],tags:[['iniciativa','sinceridad'],['observacion','analisis'],['prudencia','confianza'],['sensibilidad','analisis'],['regulacion']]},
  {q:'¿Cómo te gustaría que te recordara alguien importante?',a:['Como alguien divertido/a','Como alguien en quien podía confiar','Como alguien intenso e inolvidable','Como alguien que siempre estuvo ahí','Como alguien que le hizo descubrir cosas nuevas'],tags:[['humor'],['confianza','lealtad'],['intensidad'],['constancia','cuidado'],['curiosidad','novedad']]}
];

const traitNames=['creatividad','curiosidad','analisis','empatia','iniciativa','autonomia','sensibilidad','intensidad','humor','prudencia','sinceridad','afecto','reciprocidad','conexion','espontaneidad','seguridad','confianza','adaptacion','constancia','exclusividad','atraccion','orgullo','resolucion','sociabilidad','observacion','timidez','limites','intuicion','perfeccionismo','impulsividad','lealtad','inseguridad','validacion','expresividad','cuidado','contacto','regulacion','ocultacion','humildad','novedad'];
const base=Object.fromEntries(traitNames.map(x=>[x,50]));

function buildProfile(answers,free){const s={...base};answers.forEach((v,i)=>{(questions[i]?.tags[v]||[]).forEach(t=>s[t]=(s[t]||50)+7)});Object.keys(s).forEach(k=>s[k]=Math.max(0,Math.min(100,s[k])));if(free.trim().length>30){s.creatividad=Math.min(100,s.creatividad+4);s.curiosidad=Math.min(100,s.curiosidad+4)}return s}
function conversationSignals(text){const clean=text.trim();if(!clean)return null;const lines=clean.split(/\n+/).filter(Boolean);const words=clean.split(/\s+/).filter(Boolean);return{sampleCharacters:clean.length,lines:lines.length,averageWordsPerLine:Math.round(words.length/Math.max(lines.length,1)),questionMarks:(clean.match(/\?/g)||[]).length,exclamations:(clean.match(/!/g)||[]).length,laughter:(clean.match(/jaj|haha|jeje|lol/gi)||[]).length,emojiLike:(clean.match(/[😀-🙏🌀-🫿]/gu)||[]).length,status:'local_signals_ready_ai_pending'}}
function hiddenAnalysis(photo,conversation){return{appearance:{status:photo?'pending_ai':'not_provided',perceivedAttractiveness:null,presentation:null,visualStyle:null},communication:{status:conversation.trim()?'pending_ai':'not_provided',signals:conversationSignals(conversation),warmth:null,humor:null,directness:null,expressiveness:null,languageStyle:null},note:'Las percepciones sociales serán contextuales por personaje; no son puntuaciones objetivas.'}}

export default function Home(){
 const [step,setStep]=useState('welcome');
 const [identity,setIdentity]=useState({name:'',age:'',gender:'',orientation:'',city:'',height:'',occupation:''});
 const [sources,setSources]=useState({photo:'',conversation:''});
 const [qi,setQi]=useState(0);const [answers,setAnswers]=useState([]);const [free,setFree]=useState('');const [profile,setProfile]=useState(null);const [hidden,setHidden]=useState(null);const [unlocked,setUnlocked]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('private-life-save');if(saved){try{const x=JSON.parse(saved);setIdentity(x.identity||identity);setSources(x.sources||{photo:'',conversation:''});setProfile(x.profile||null);setHidden(x.hidden||null);if(x.profile)setStep('lock')}catch{}}},[]);
 const valid=identity.name.trim()&&Number(identity.age)>=18&&identity.city.trim();
 const traits=useMemo(()=>profile?Object.entries(profile).sort((a,b)=>b[1]-a[1]).slice(0,5):[],[profile]);
 function answer(n){const a=[...answers];a[qi]=n;setAnswers(a);if(qi<questions.length-1)setQi(qi+1);else setStep('free')}
 function finish(){const p=buildProfile(answers,free);setProfile(p);setHidden(hiddenAnalysis(sources.photo,sources.conversation));setStep('profile')}
 function confirm(){const save={identity,sources,profile,hidden,free};try{localStorage.setItem('private-life-save',JSON.stringify(save))}catch{const lean={...save,sources:{...sources,photo:''}};localStorage.setItem('private-life-save',JSON.stringify(lean))}setStep('boot');setTimeout(()=>setStep('lock'),2300)}
 function photoPicked(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=420,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);setSources(s=>({...s,photo:c.toDataURL('image/jpeg',.76)}))};img.src=reader.result};reader.readAsDataURL(file)}
 function historyPicked(file){if(!file)return;const reader=new FileReader();reader.onload=()=>setSources(s=>({...s,conversation:String(reader.result).slice(0,60000)}));reader.readAsText(file)}
 if(step==='welcome')return <main className="center intro"><div className="brand">PRIVATE <b>LIFE</b></div><p>Esta historia no está escrita todavía.</p><p className="muted">Empecemos por ti.</p><button onClick={()=>setStep('identity')}>NUEVA PARTIDA</button></main>;
 if(step==='identity')return <main className="wizard"><Progress n={1}/><h1>¿Quién eres?</h1><p className="muted">Crea al adulto que vivirá esta historia.</p><div className="form"><Input label="Nombre" value={identity.name} set={v=>setIdentity({...identity,name:v})}/><Input label="Edad (18+)" type="number" value={identity.age} set={v=>setIdentity({...identity,age:v})}/><Input label="Ciudad" value={identity.city} set={v=>setIdentity({...identity,city:v})}/><Input label="Ocupación" value={identity.occupation} set={v=>setIdentity({...identity,occupation:v})}/><Input label="Altura" value={identity.height} set={v=>setIdentity({...identity,height:v})}/><Input label="Género" value={identity.gender} set={v=>setIdentity({...identity,gender:v})}/><Input label="Orientación" value={identity.orientation} set={v=>setIdentity({...identity,orientation:v})}/></div><button disabled={!valid} onClick={()=>setStep('sources')}>CONTINUAR</button></main>;
 if(step==='sources')return <main className="wizard"><Progress n={2}/><h1>Danos contexto</h1><p className="muted">Opcional. Una foto y una conversación real ayudan a construir una representación más personal del personaje.</p><div className="sourcegrid"><section className="sourcecard"><div className="sourcehead"><b>FOTO DE PERFIL</b><span>OPCIONAL</span></div>{sources.photo?<img className="avatarpreview" src={sources.photo} alt="Vista previa del personaje"/>:<div className="avatarblank">+</div>}<label className="filebutton">{sources.photo?'CAMBIAR FOTO':'AÑADIR FOTO'}<input type="file" accept="image/*" onChange={e=>photoPicked(e.target.files?.[0])}/></label>{sources.photo&&<button className="remove" onClick={()=>setSources({...sources,photo:''})}>Quitar</button>}</section><section className="sourcecard wide"><div className="sourcehead"><b>HISTORIAL DE CONVERSACIÓN</b><span>OPCIONAL</span></div><p className="muted small">Pega mensajes o importa un .txt/.md. Servirá para estudiar estilo de escritura, humor, expresividad y patrones de conversación.</p><textarea className="history" placeholder="Pega aquí una conversación exportada..." value={sources.conversation} onChange={e=>setSources({...sources,conversation:e.target.value.slice(0,60000)})}/><label className="filebutton">IMPORTAR ARCHIVO<input type="file" accept=".txt,.md,text/plain" onChange={e=>historyPicked(e.target.files?.[0])}/></label><div className="charcount">{sources.conversation.length.toLocaleString()} / 60.000 caracteres</div></section></div><div className="privacy">La foto y el historial son opcionales. En esta versión se guardan localmente en este dispositivo. La futura IA utilizará estas fuentes en segundo plano para construir percepciones contextuales, no una nota objetiva de belleza o personalidad.</div><button onClick={()=>setStep('quiz')}>CONTINUAR</button></main>;
 if(step==='quiz'){const q=questions[qi];return <main className="wizard"><Progress n={3}/><div className="counter">PREGUNTA {qi+1} / {questions.length}</div><h1>{q.q}</h1><div className="answers">{q.a.map((x,i)=><button className="answer" key={x} onClick={()=>answer(i)}>{x}</button>)}</div>{qi>0&&<button className="ghost" onClick={()=>setQi(qi-1)}>Atrás</button>}</main>}
 if(step==='free')return <main className="wizard"><Progress n={4}/><h1>Algo que debamos saber de ti</h1><p className="muted">Cuéntanos lo que las preguntas no hayan captado. Es opcional.</p><textarea placeholder="Soy músico, me encanta..." value={free} onChange={e=>setFree(e.target.value)}/><button onClick={finish}>CREAR MI PERSONAJE</button></main>;
 if(step==='profile')return <main className="wizard"><div className="eyebrow">PERSONAJE CREADO</div><div className="profiletitle">{sources.photo&&<img src={sources.photo} alt="Perfil"/>}<h1>{identity.name.toUpperCase()} <span className="thin">· {identity.age} · {identity.city}</span></h1></div><div className="card"><h3>RASGOS DESTACADOS</h3><div className="chips">{traits.map(([k])=><span key={k}>{k}</span>)}</div><h3>PERFIL</h3><p>Tu personaje reaccionará según sus rasgos, recuerdos, forma de comunicarse y decisiones. La ficha interna evolucionará mientras juegas.</p><p className="muted small">Las variables completas y el análisis de percepción permanecerán ocultos durante la partida.</p></div><button onClick={confirm}>ESTE SOY YO</button></main>;
 if(step==='boot')return <main className="center boot"><div className="orb">P</div><div className="brand smallbrand">PRIVATE LIFE</div><p className="muted">Configurando tu vida...</p><div className="loader"><i/></div></main>;
 if(step==='lock'&&!unlocked)return <Phone><div className="lock" onClick={()=>setUnlocked(true)}><Status/><div className="locktime">09:41</div><div className="date">Domingo, 27 de septiembre</div><div className="lockbrand">PRIVATE LIFE</div><div className="swipe">⌃<br/><span>Toca para desbloquear</span></div></div></Phone>;
 return <Phone><div className="home"><Status/><div className="hello">Buenos días, <b>{identity.name}</b></div><div className="apps"><App icon="◎" name="Social"/><App icon="●" name="Chat"/><App icon="☎" name="Teléfono"/><App icon="♟" name="Contactos"/><App icon="▧" name="Galería"/><App icon="□" name="Agenda"/><App icon="≡" name="Notas"/><App icon="⚙" name="Ajustes"/></div><div className="dock"><App icon="☎" name=""/><App icon="●" name=""/><App icon="◎" name=""/></div></div></Phone>;
}
function Progress({n}){return <div className="progress">{[1,2,3,4].map(x=><i key={x} className={x<=n?'on':''}/>)}</div>}
function Input({label,value,set,type='text'}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Phone({children}){return <main className="stage"><div className="phone">{children}<div className="gesture"/></div></main>}
function Status(){return <div className="status"><b>09:41</b><span>● ◔ 100%</span></div>}
function App({icon,name}){return <div className="app"><div className="appicon">{icon}</div>{name&&<span>{name}</span>}</div>}
