'use client';

import { useEffect, useMemo, useState } from 'react';

const questions = [
  { q:'Una persona importante lleva horas sin contestarte. ¿Qué piensas primero?', a:['Estará ocupada','Me pregunto si habrá pasado algo','Repaso nuestra última conversación','Me molesta, aunque intento ignorarlo','Apenas le doy importancia'], tags:[['seguridad'],['empatia','sensibilidad'],['analisis','sensibilidad'],['intensidad'],['autonomia']] },
  { q:'Cuando alguien empieza a gustarte, normalmente...', a:['Tomo la iniciativa','Observo primero','Coqueteo para tantear','Intento disimularlo','Depende muchísimo de la persona'], tags:[['iniciativa'],['analisis'],['humor','iniciativa'],['prudencia'],['adaptacion']] },
  { q:'¿Qué valoras más en una relación?', a:['Constancia','Sinceridad','Libertad','Afecto','Intensidad'], tags:[['constancia'],['sinceridad'],['autonomia'],['afecto'],['intensidad']] },
  { q:'Una discusión importante aparece. Tú...', a:['Quiero resolverla cuanto antes','Necesito tiempo para pensar','Pregunto hasta entender qué ocurre','Intento rebajarla con humor','Me cierro si me siento atacado/a'], tags:[['resolucion'],['prudencia'],['analisis'],['humor'],['sensibilidad']] },
  { q:'¿Qué te cuesta más perdonar?', a:['Una mentira','La indiferencia','Una infidelidad','Una humillación','Que desaparezcan sin explicar nada'], tags:[['sinceridad'],['afecto'],['exclusividad'],['orgullo'],['sensibilidad']] },
  { q:'¿Cuánto pesa la atracción física para ti?', a:['Muy poco','Algo, pero manda la conexión','Importa bastante','Es esencial al principio','Depende totalmente de la persona'], tags:[['conexion'],['conexion'],['atraccion'],['atraccion'],['adaptacion']] },
  { q:'Cuando hay química con alguien...', a:['Voy despacio','Dejo que fluya','Suelo tomar iniciativa','Espero señales claras','Me pongo bastante nervioso/a'], tags:[['prudencia'],['espontaneidad'],['iniciativa'],['reciprocidad'],['sensibilidad']] },
  { q:'¿Qué necesitas para abrirte de verdad?', a:['Tiempo','Confianza','Sentirme escuchado/a','Reciprocidad','Que la otra persona se abra primero'], tags:[['prudencia'],['confianza'],['conexion'],['reciprocidad'],['reciprocidad']] },
  { q:'Si notas un cambio de tono en alguien importante...', a:['Pregunto directamente','Espero a ver qué ocurre','Le doy muchas vueltas','Asumo que tendrá un mal día','Me distancio también'], tags:[['iniciativa'],['prudencia'],['analisis'],['seguridad'],['orgullo']] },
  { q:'Tu relación ideal deja espacio para...', a:['Muchísima independencia','Rutinas compartidas','Hablar todos los días','Improvisar y sorprendernos','Una mezcla de todo'], tags:[['autonomia'],['constancia'],['afecto'],['espontaneidad'],['adaptacion']] },
  { q:'¿Cómo te llevas con la incertidumbre?', a:['Muy bien','Bastante bien','Depende','Me cuesta','La odio'], tags:[['seguridad'],['autonomia'],['adaptacion'],['analisis'],['analisis','sensibilidad']] },
  { q:'Si alguien te atrae pero no sabes si es recíproco...', a:['Se lo digo','Lanzo indirectas','Espero señales','Intento olvidarlo','Sigo conociéndolo sin decidir nada'], tags:[['iniciativa'],['humor'],['reciprocidad'],['autonomia'],['curiosidad']] },
];

const base = { creatividad:50, curiosidad:50, analisis:50, empatia:50, iniciativa:50, autonomia:50, sensibilidad:50, intensidad:50, humor:50, prudencia:50, sinceridad:50, afecto:50, reciprocidad:50, conexion:50, espontaneidad:50, seguridad:50, confianza:50, adaptacion:50, constancia:50, exclusividad:50, atraccion:50, orgullo:50, resolucion:50 };

function buildProfile(answers, free){ const s={...base}; answers.forEach((v,i)=>{(questions[i]?.tags[v]||[]).forEach(t=>s[t]=(s[t]||50)+8)}); Object.keys(s).forEach(k=>s[k]=Math.max(0,Math.min(100,s[k]))); if(free.trim().length>30){s.creatividad+=4;s.curiosidad+=4;} return s; }

export default function Home(){
 const [step,setStep]=useState('welcome'); const [identity,setIdentity]=useState({name:'',age:'',gender:'',orientation:'',city:'',height:'',occupation:''}); const [qi,setQi]=useState(0); const [answers,setAnswers]=useState([]); const [free,setFree]=useState(''); const [profile,setProfile]=useState(null); const [unlocked,setUnlocked]=useState(false); const [time,setTime]=useState('09:41');
 useEffect(()=>{ const saved=localStorage.getItem('private-life-save'); if(saved){try{const x=JSON.parse(saved);setIdentity(x.identity||identity);setProfile(x.profile||null);if(x.profile)setStep('lock')}catch{}} },[]);
 const valid=identity.name.trim() && Number(identity.age)>=18 && identity.city.trim();
 const traits=useMemo(()=>profile?Object.entries(profile).sort((a,b)=>b[1]-a[1]).slice(0,5):[],[profile]);
 function answer(n){const a=[...answers];a[qi]=n;setAnswers(a);if(qi<questions.length-1)setQi(qi+1);else setStep('free')}
 function finish(){const p=buildProfile(answers,free);setProfile(p);setStep('profile')}
 function confirm(){localStorage.setItem('private-life-save',JSON.stringify({identity,profile}));setStep('boot');setTimeout(()=>setStep('lock'),2300)}
 if(step==='welcome') return <main className="center intro"><div className="brand">PRIVATE <b>LIFE</b></div><p>Esta historia no está escrita todavía.</p><p className="muted">Empecemos por ti.</p><button onClick={()=>setStep('identity')}>NUEVA PARTIDA</button></main>;
 if(step==='identity') return <main className="wizard"><Progress n={1}/><h1>¿Quién eres?</h1><p className="muted">Crea al adulto que vivirá esta historia.</p><div className="form"><Input label="Nombre" value={identity.name} set={v=>setIdentity({...identity,name:v})}/><Input label="Edad (18+)" type="number" value={identity.age} set={v=>setIdentity({...identity,age:v})}/><Input label="Ciudad" value={identity.city} set={v=>setIdentity({...identity,city:v})}/><Input label="Ocupación" value={identity.occupation} set={v=>setIdentity({...identity,occupation:v})}/><Input label="Altura" value={identity.height} set={v=>setIdentity({...identity,height:v})}/><Input label="Género" value={identity.gender} set={v=>setIdentity({...identity,gender:v})}/><Input label="Orientación" value={identity.orientation} set={v=>setIdentity({...identity,orientation:v})}/></div><button disabled={!valid} onClick={()=>setStep('quiz')}>CONTINUAR</button></main>;
 if(step==='quiz'){const q=questions[qi];return <main className="wizard"><Progress n={2}/><div className="counter">PREGUNTA {qi+1} / {questions.length}</div><h1>{q.q}</h1><div className="answers">{q.a.map((x,i)=><button className="answer" key={x} onClick={()=>answer(i)}>{x}</button>)}</div>{qi>0&&<button className="ghost" onClick={()=>setQi(qi-1)}>Atrás</button>}</main>}
 if(step==='free') return <main className="wizard"><Progress n={3}/><h1>Algo que debamos saber de ti</h1><p className="muted">Cuéntanos lo que las preguntas no hayan captado. Es opcional.</p><textarea placeholder="Soy músico, me encanta..." value={free} onChange={e=>setFree(e.target.value)}/><button onClick={finish}>CREAR MI PERSONAJE</button></main>;
 if(step==='profile') return <main className="wizard"><div className="eyebrow">PERSONAJE CREADO</div><h1>{identity.name.toUpperCase()} <span className="thin">· {identity.age} · {identity.city}</span></h1><div className="card"><h3>RASGOS DESTACADOS</h3><div className="chips">{traits.map(([k])=><span key={k}>{k}</span>)}</div><h3>PERFIL</h3><p>Tu personaje reaccionará según sus rasgos, recuerdos y decisiones. La ficha interna evolucionará mientras juegas.</p><p className="muted small">Las variables completas permanecerán ocultas durante la partida.</p></div><button onClick={confirm}>ESTE SOY YO</button></main>;
 if(step==='boot') return <main className="center boot"><div className="orb">P</div><div className="brand smallbrand">PRIVATE LIFE</div><p className="muted">Configurando tu vida...</p><div className="loader"><i/></div></main>;
 if(step==='lock'&&!unlocked) return <Phone><div className="lock" onClick={()=>setUnlocked(true)}><Status/><div className="locktime">09:41</div><div className="date">Domingo, 27 de septiembre</div><div className="lockbrand">PRIVATE LIFE</div><div className="swipe">⌃<br/><span>Toca para desbloquear</span></div></div></Phone>;
 return <Phone><div className="home"><Status/><div className="hello">Buenos días, <b>{identity.name}</b></div><div className="apps"><App icon="◎" name="Social"/><App icon="●" name="Chat"/><App icon="☎" name="Teléfono"/><App icon="♟" name="Contactos"/><App icon="▧" name="Galería"/><App icon="□" name="Agenda"/><App icon="≡" name="Notas"/><App icon="⚙" name="Ajustes"/></div><div className="dock"><App icon="☎" name=""/><App icon="●" name=""/><App icon="◎" name=""/></div></div></Phone>;
}
function Progress({n}){return <div className="progress">{[1,2,3].map(x=><i key={x} className={x<=n?'on':''}/>)}</div>}
function Input({label,value,set,type='text'}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Phone({children}){return <main className="stage"><div className="phone">{children}<div className="gesture"/></div></main>}
function Status(){return <div className="status"><b>09:41</b><span>● ◔ 100%</span></div>}
function App({icon,name}){return <div className="app"><div className="appicon">{icon}</div>{name&&<span>{name}</span>}</div>}
