'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import './notas.css';

const CONTACTS='private-life-contacts';
const EVENTS='private-life-narrative-events-v1';
const WHATSAPP='private-life-whatsapp-v1';
function read(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x??fallback}catch{return fallback}}
function snapshot(){
 const contacts=read(CONTACTS,[]),chats=read(WHATSAPP,{}),events=read(EVENTS,[]);
 const safeContacts=(Array.isArray(contacts)?contacts:[]).filter(c=>c?.name&&Number(c?.age)>=18).slice(0,20).map(c=>({id:c.id,name:c.name,age:c.age,city:c.city,relationshipType:c.relationshipType,relation:c.relation,affection:c.affection,sourceType:c.sourceType,profile:c.profile,notes:c.notes,engineContext:c.engineContext,masterSheet:c.masterSheet,conversation:String(c.conversation||'').slice(0,12000),photoCount:Array.isArray(c.photos)?c.photos.length:0}));
 const whatsapp=safeContacts.map(c=>({contactName:c.name,messages:Array.isArray(chats?.[c.id]?.messages)?chats[c.id].messages.slice(-18).map(m=>({side:m.side,type:m.type,text:String(m.text||'').slice(0,700),createdAt:m.createdAt})):[]})).filter(x=>x.messages.length);
 return{contacts:safeContacts,narrativeEvents:(Array.isArray(events)?events:[]).slice(0,120),whatsapp};
}
function syncStoryContacts(payload){
 const unlocks=Array.isArray(payload?.contactUnlocks)?payload.contactUnlocks:[];if(!unlocks.length)return;
 const current=read(CONTACTS,[]),list=Array.isArray(current)?[...current]:[];let changed=false;
 for(const u of unlocks){if(!u?.name||Number(u.age)<18)continue;const exists=list.some(c=>String(c.sourceCharacterId||'')===String(u.characterId||'')||(c.sourceType==='Personaje IA'&&String(c.name||'').toLowerCase()===String(u.name).toLowerCase()));if(exists)continue;list.push({id:`story-${u.characterId||crypto.randomUUID?.()||Date.now()}`,sourceCharacterId:u.characterId||'',name:u.name,age:u.age,city:u.city||'',relationshipType:u.relationshipType||'Conocido/a',relation:u.relation||'Conocido durante la historia',affection:Number(u.affection)||50,notes:'Contacto incorporado por un acontecimiento de la historia.',conversation:'',photos:[],profile:u.profile||'',consent:true,test:[],sourceType:'Personaje IA',masterSheet:null,engineContext:u.engineContext||'',updatedAt:new Date().toISOString()});changed=true}
 if(changed){try{localStorage.setItem(CONTACTS,JSON.stringify(list));window.dispatchEvent(new CustomEvent('private-life:contacts-changed',{detail:{count:list.length,source:'narrator'}}))}catch{}}
}
function applyConsequences(payload){syncStoryContacts(payload);for(const n of Array.isArray(payload?.notifications)?payload.notifications:[])window.privateLifeNotify?.({app:n.app||'PRIVATE LIFE',title:n.title||n.app||'PRIVATE LIFE',body:n.body||'',priority:n.priority||'normal'})}
function StoryText({text}){const blocks=String(text||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);return <div className="storyText">{(blocks.length?blocks:[String(text||'')]).map((p,i)=><p key={i}>{p}</p>)}</div>}

export default function Notes(){
 const[save,setSave]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mode,setMode]=useState('notes'),[busy,setBusy]=useState(false),[archive,setArchive]=useState(null);
 const started=useRef(false);
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/save',{cache:'no-store'});if(!r.ok)throw new Error('No se pudo cargar la partida.');const x=await r.json();setSave(x.save);if(x.save?.gameplay?.narratorMode)setMode('narrator')}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
 const narrator=save?.narrator||{chapter:1,turn:0,history:[],chapters:[],hidden:{},currentScene:null};
 const scene=narrator.currentScene||null,chapters=Array.isArray(narrator.chapters)?narrator.chapters:[];
 const contacts=useMemo(()=>snapshot().contacts,[mode,save?.social?.contactsUpdatedAt]);
 const currentPart=(Number(narrator.turn)||0)%5+1;
 async function write(next){setBusy(true);try{const r=await fetch('/api/save',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({save:next})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'No se pudo guardar.');setSave(next);return next}catch(e){setError(e.message);return null}finally{setBusy(false)}}
 async function generate(action='start',choice=''){
  if(busy)return;setBusy(true);setError('');
  try{const r=await fetch('/api/narrator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,choice,clientContext:snapshot()})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'No se pudo generar la historia.');applyConsequences(x);setSave(x.save);return x}catch(e){setError(e.message);return null}finally{setBusy(false)}
 }
 useEffect(()=>{if(mode!=='narrator'||!save||scene||started.current)return;started.current=true;generate('start')},[mode,save,scene]);
 async function activate(){if(!save)return;const next={...save,gameplay:{...(save.gameplay||{}),narratorMode:true,narratorActivatedAt:save.gameplay?.narratorActivatedAt||new Date().toISOString()},narrator:save.narrator||{chapter:1,turn:0,history:[],chapters:[],hidden:{},currentScene:null}};const ok=await write(next);if(ok){setMode('narrator');started.current=true;await generate('start')}}
 async function deactivate(){if(!save)return;const next={...save,gameplay:{...(save.gameplay||{}),narratorMode:false}};await write(next);setMode('notes');started.current=false}
 async function choose(label){if(busy||!scene)return;await generate('continue',label)}
 async function regenerate(){if(busy)return;await generate('start','')}
 if(loading)return <main className="notesLoading">Abriendo Notas…</main>;
 if(error&&!save)return <main className="notesLoading"><div>{error}</div><button onClick={()=>location.href='/'}>VOLVER</button></main>;
 if(archive){const ch=chapters.find(c=>Number(c.number)===Number(archive));return <main className="chapterReader"><header className="notesTop"><button className="pl-unified-back" onClick={()=>setArchive(null)}>‹</button><b>Capítulo {ch?.number}</b><span>•••</span></header><div className="chapterPaper"><small>PRIVATE LIFE · HISTORIA</small><h1>{ch?.title||`Capítulo ${ch?.number}`}</h1>{(ch?.parts||[]).map((p,i)=><article key={`${p.at}-${i}`}><div>PARTE {p.part||i+1}</div><h2>{p.scene}</h2><StoryText text={p.text}/><blockquote>Elegiste: {p.choice}</blockquote></article>)}{!ch?.completedAt&&<div className="chapterOpen">Capítulo en curso</div>}</div></main>}
 if(mode==='narrator')return <main className="narrator"><header className="narratorTop"><button className="pl-unified-back" aria-label="Volver" onClick={()=>location.href='/'}>‹</button><div><small>MODO NARRADOR</small><b>Capítulo {narrator.chapter} · Parte {currentPart}/5</b></div><button className="exit" onClick={deactivate}>NOTAS</button></header><div className="narratorBody"><div className="chapterMark">{narrator.chapterTitle||`PRIVATE LIFE · CAPÍTULO ${narrator.chapter}`}</div>{!scene?<article className="story"><span>IA CENTRAL</span><h1>{busy?'Escribiendo una parte completa…':'La historia espera tu siguiente paso'}</h1><p>{busy?'La Central está preparando el contexto y la Narradora está escribiendo la escena completa. Puede tardar algo más porque ya no genera resúmenes breves.':'Continúa para reanudar el capítulo.'}</p>{!busy&&<button onClick={()=>generate('start')}>CONTINUAR</button>}</article>:<><article className="story"><span>PARTE {currentPart}</span><h1>{scene.title}</h1><StoryText text={scene.text}/></article><div className="choices">{(scene.choices||[]).map((choice,i)=><button key={`${choice.label}-${i}`} disabled={busy} onClick={()=>choose(choice.label)}><i>{String.fromCharCode(65+i)}</i><span>{choice.label}</span></button>)}</div><button className="regenerateScene" disabled={busy} onClick={regenerate}>{busy?'ESCRIBIENDO…':'REESCRIBIR ESTA PARTE'}</button></>}
 <p className="hiddenHint">Tus decisiones alteran relaciones y estados que el juego no te enseña directamente. Si la historia hace que intercambies contacto con alguien, esa misma persona aparecerá después en Contactos y podrá continuar su vida en WhatsApp y el resto del juego.</p>{error&&<div className="notesError">{error}</div>}{narrator.history?.length>0&&<details className="history"><summary>Decisiones anteriores</summary>{narrator.history.slice(-8).reverse().map((h,i)=><div key={`${h.at}-${i}`}><small>C{h.chapter} · P{h.part||1}</small><span>{h.choice}</span></div>)}</details>}</div></main>;
 return <main className="notesApp"><header className="notesTop"><button className="pl-unified-back" aria-label="Volver" onClick={()=>location.href='/'}>‹</button><b>Notas</b><span>•••</span></header><div className="notesTitle"><h1>Notas</h1><span className="notesCount">{chapters.length}</span></div><div className="notesSearch">⌕ <span>Buscar</span></div><section className="notesFolder"><div className="folderHead"><b>Notas</b><span>{chapters.length+1}</span></div><button className="noteRow narratorRow" onClick={activate} disabled={busy}><i>•</i><div><b>Modo Narrador</b><small>PRIVATE LIFE · {save?.gameplay?.narratorMode?'Continuar historia':'Generar historia por capítulos'}</small></div><span>›</span></button>{[...chapters].reverse().map(ch=><button className="noteRow" key={ch.number} onClick={()=>setArchive(ch.number)}><i>•</i><div><b>Capítulo {ch.number}: {ch.title||'Sin título'}</b><small>{ch.completedAt?'Completado':`${(ch.parts||[]).length}/5 partes`} · {(ch.parts||[]).at(-1)?.scene||'Historia en curso'}</small></div><span>›</span></button>)}</section><section className="modePanel compact"><p>La historia utiliza el análisis profundo del jugador y sus contactos. Las barras emocionales y relacionales permanecen ocultas y sus consecuencias aparecen en la narración, los contactos y las aplicaciones.</p><small>{contacts.length} contactos actuales · {save?.world?.characters?.length||0} personajes en el mundo</small></section>{error&&<div className="notesError">{error}</div>}</main>;
}
